// Dữ liệu mẫu khởi tạo cho Hệ thống quản lý
const INITIAL_DATA = {
  master: [
    {
      tt: 1,
      maBsc: "CT-01",
      goiThauPl: "Xây dựng",
      nhomCt: "Dự án VSV-A",
      hangMuc: "Thi công cọc nhồi và tường vây",
      phuTrach: "Nguyễn Văn A",
      ngayBdYc: "2026-01-10",
      ngayKtYc: "2026-04-15",
      nganSach: 45.0,
      khHstktc: "2025-12-15",
      ttHstktc: "Đã duyệt",
      ttSpecs: "Đã duyệt",
      ttBoq: "Đã chốt",
      khLcnt: "2025-12-20",
      ttLcnt: "Đã có KQ",
      khHdcu: "2026-01-05",
      ttHdcu: "Đã ký",
      khPdKhcu: "2026-01-08",
      ttKhcu: "Đã phê duyệt",
      giaTriHdcu: 42.5,
      khPlhdCdt: "2026-01-08",
      ttPlhdCdt: "Đã ký",
      khPdKhtk: "2026-01-09",
      ttKhtk: "Đã duyệt",
      dk1: "Đạt",
      dk2: "Đạt",
      dk3: "Đạt",
      ngayBdKhoiCong: "2026-01-12",
      luyKeGiaTriHdAB: 42.5,
      buTienDo: "Không chạy",
      khQaQc: "Hoàn thành nghiệm thu 100% lồng thép cọc đại trà",
      kqQaQc: "Đạt yêu cầu chất lượng, hồ sơ thí nghiệm đầy đủ",
      dgQaQc: "Kiểm soát tốt chất lượng vật liệu đầu vào",
      khThiCong: "Khoan 45 cọc nhồi đường kính D1200",
      kqThiCong: "Hoàn thành khoan 45 cọc, vượt tiến độ 2 ngày",
      dgThiCong: "Biện pháp thi công hợp lý, máy móc hoạt động ổn định",
      t1Kh: "Khoan cọc nhồi từ tim 1 đến tim 10",
      t1Kq: "Hoàn thành 10 cọc",
      t1Dg: "Đạt",
      t2Kh: "Khoan cọc nhồi từ tim 11 đến tim 25",
      t2Kq: "Hoàn thành 15 cọc",
      t2Dg: "Đạt",
      t3Kh: "Khoan cọc nhồi từ tim 26 đến tim 35",
      t3Kq: "Hoàn thành 10 cọc",
      t3Dg: "Đạt",
      t4Kh: "Khoan cọc nhồi từ tim 36 đến tim 45",
      t4Kq: "Hoàn thành 10 cọc",
      t4Dg: "Đạt"
    },
    {
      tt: 2,
      maBsc: "CT-02",
      goiThauPl: "Cơ điện",
      nhomCt: "Dự án VSV-A",
      hangMuc: "Cung cấp và lắp đặt hệ thống Trạm biến áp",
      phuTrach: "Trần Thị B",
      ngayBdYc: "2026-03-01",
      ngayKtYc: "2026-08-30",
      nganSach: 18.5,
      khHstktc: "2026-01-15",
      ttHstktc: "Đã duyệt",
      ttSpecs: "Đã duyệt",
      ttBoq: "Đã chốt",
      khLcnt: "2026-02-10",
      ttLcnt: "Đã có KQ",
      khHdcu: "2026-02-25",
      ttHdcu: "Đã ký",
      khPdKhcu: "2026-02-28",
      ttKhcu: "Đã phê duyệt",
      giaTriHdcu: 17.8,
      khPlhdCdt: "2026-03-01",
      ttPlhdCdt: "Đã ký",
      khPdKhtk: "2026-03-02",
      ttKhtk: "Đã duyệt",
      dk1: "Đạt",
      dk2: "Đạt",
      dk3: "Đạt",
      ngayBdKhoiCong: "2026-03-05",
      luyKeGiaTriHdAB: 17.8,
      buTienDo: "Chậm tiến độ",
      khQaQc: "Kiểm tra xuất xưởng thiết bị đóng cắt tủ trung thế",
      kqQaQc: "Chưa có chứng nhận CO/CQ bản gốc từ nhà cung cấp",
      dgQaQc: "Yêu cầu nhà thầu bổ sung gấp trước khi đưa về công trình",
      khThiCong: "Kéo rải cáp ngầm trung thế từ trạm chính về tủ phân phối",
      kqThiCong: "Chậm tiến độ do thời tiết mưa kéo dài, sạt lở mương cáp",
      dgThiCong: "Nhà thầu cần bổ sung bạt che và máy bơm hút nước để thi công",
      t1Kh: "Đào rãnh cáp sâu 1.2m dài 200m",
      t1Kq: "Đào được 150m, gặp đá mồ côi cần đục tay",
      t1Dg: "Chậm",
      t2Kh: "Rải cát đệm và đặt ống nhựa HDPE",
      t2Kq: "Đã rải cát 150m và đặt ống",
      t2Dg: "Đạt",
      t3Kh: "Kéo rải cáp ngầm tổng chiều dài 400m",
      t3Kq: "Mới kéo được 200m, chậm do thiếu nhân lực",
      t3Dg: "Cần hỗ trợ",
      t4Kh: "Đấu nối đầu cáp trung thế vào tủ",
      t4Kq: "Chưa thực hiện được do cáp chưa kéo xong",
      t4Dg: "Chậm"
    },
    {
      tt: 3,
      maBsc: "CT-03",
      goiThauPl: "Hoàn thiện",
      nhomCt: "Dự án VSV-B",
      hangMuc: "Trát tường, ốp lát granite sảnh chính",
      phuTrach: "Lê Văn C",
      ngayBdYc: "2026-05-10",
      ngayKtYc: "2026-09-30",
      nganSach: 22.0,
      khHstktc: "2026-04-10",
      ttHstktc: "Đang trình duyệt",
      ttSpecs: "Đang kiểm tra",
      ttBoq: "Đang thẩm tra",
      khLcnt: "2026-05-01",
      ttLcnt: "Đang mời thầu",
      khHdcu: "2026-05-15",
      ttHdcu: "Đang thương thảo",
      khPdKhcu: "2026-05-10",
      ttKhcu: "Đang duyệt",
      giaTriHdcu: 0,
      khPlhdCdt: "2026-05-20",
      ttPlhdCdt: "Chưa ký",
      khPdKhtk: "2026-05-20",
      ttKhtk: "Chưa lập",
      dk1: "Chưa đạt",
      dk2: "Chưa đạt",
      dk3: "Chưa đạt",
      ngayBdKhoiCong: "",
      luyKeGiaTriHdAB: 0,
      buTienDo: "Không chạy",
      khQaQc: "Kiểm tra mẫu đá granite nhập khẩu",
      kqQaQc: "Đang chờ kết quả thí nghiệm cường độ uốn",
      dgQaQc: "Cần đốc thúc đơn vị thí nghiệm trả kết quả sớm",
      khThiCong: "Trát tường ngoài nhà hướng Đông",
      kqThiCong: "Chưa khởi công do chưa có nhà thầu chính thức",
      dgThiCong: "Đang đẩy nhanh tiến độ lựa chọn nhà thầu",
      t1Kh: "Duyệt mẫu vật liệu granite sảnh chính",
      t1Kq: "Đang trình mẫu 3 đơn vị cung cấp",
      t1Dg: "Cần hỗ trợ",
      t2Kh: "Ký kết hợp đồng thi công hoàn thiện",
      t2Kq: "Đang đàm phán điều khoản thanh toán",
      t2Dg: "Cần hỗ trợ",
      t3Kh: "Lập phương án giàn giáo ngoài nhà",
      t3Kq: "Chưa thực hiện",
      t3Dg: "Chậm",
      t4Kh: "Nhập đá granite đợt 1 về kho công trình",
      t4Kq: "Chưa thực hiện",
      t4Dg: "Chậm"
    },
    {
      tt: 4,
      maBsc: "CT-04",
      goiThauPl: "Thiết bị",
      nhomCt: "Dự án VSV-C",
      hangMuc: "Cung cấp và lắp đặt hệ thống Điều hòa thông gió Chiller",
      phuTrach: "Phạm Văn D",
      ngayBdYc: "2026-06-01",
      ngayKtYc: "2026-12-15",
      nganSach: 35.0,
      khHstktc: "2026-03-20",
      ttHstktc: "Đã duyệt",
      ttSpecs: "Đã duyệt",
      ttBoq: "Đã chốt",
      khLcnt: "2026-04-15",
      ttLcnt: "Đã có KQ",
      khHdcu: "2026-05-10",
      ttHdcu: "Đã ký",
      khPdKhcu: "2026-05-15",
      ttKhcu: "Đã phê duyệt",
      giaTriHdcu: 33.2,
      khPlhdCdt: "2026-05-25",
      ttPlhdCdt: "Đã ký",
      khPdKhtk: "2026-05-28",
      ttKhtk: "Đang thẩm định",
      dk1: "Đạt",
      dk2: "Đạt",
      dk3: "Chưa đạt",
      ngayBdKhoiCong: "",
      luyKeGiaTriHdAB: 33.2,
      buTienDo: "Không chạy",
      khQaQc: "Kiểm tra bản vẽ thi công Shopdrawing hệ ống gió",
      kqQaQc: "Còn một số vị trí xung đột với đường ống chữa cháy",
      dgQaQc: "Yêu cầu thiết kế phối hợp điều chỉnh cao độ cao ống",
      khThiCong: "Gia công chế tạo ống gió tôn mạ kẽm tại xưởng",
      kqThiCong: "Đã hoàn thành chế tạo 800m2 ống gió chuẩn bị giao",
      dgThiCong: "Sản xuất đúng tiến độ và tiêu chuẩn kích thước bản vẽ",
      t1Kh: "Trình duyệt bản vẽ thi công hệ Chiller",
      t1Kq: "Đã trình duyệt bản vẽ hiệu chỉnh lần 2",
      t1Dg: "Đạt",
      t2Kh: "Gia công ống gió tôn tại xưởng",
      t2Kq: "Hoàn thành 50% khối lượng gia công",
      t2Dg: "Đạt",
      t3Kh: "Nhập máy Chiller thương hiệu Daikin về cảng",
      t3Kq: "Máy đã cập cảng Hải Phòng, đang làm thủ tục thông quan",
      t3Dg: "Đạt",
      t4Kh: "Vận chuyển máy Chiller lắp đặt vào bệ móng",
      t4Kq: "Chưa thực hiện do bệ máy chưa đạt tuổi bê tông",
      t4Dg: "Cần hỗ trợ"
    },
    {
      tt: 5,
      maBsc: "CT-05",
      goiThauPl: "Khác",
      nhomCt: "Dự án VSV-B",
      hangMuc: "Thi công đường nội bộ và hạ tầng cảnh quan",
      phuTrach: "Hoàng Văn E",
      ngayBdYc: "2026-04-01",
      ngayKtYc: "2026-08-30",
      nganSach: 15.0,
      khHstktc: "2026-02-28",
      ttHstktc: "Đã duyệt",
      ttSpecs: "Đã duyệt",
      ttBoq: "Đã chốt",
      khLcnt: "2026-03-10",
      ttLcnt: "Đã có KQ",
      khHdcu: "2026-03-25",
      ttHdcu: "Đã ký",
      khPdKhcu: "2026-03-28",
      ttKhcu: "Đã phê duyệt",
      giaTriHdcu: 14.5,
      khPlhdCdt: "2026-04-01",
      ttPlhdCdt: "Đã ký",
      khPdKhtk: "2026-04-05",
      ttKhtk: "Đã duyệt",
      dk1: "Đạt",
      dk2: "Đạt",
      dk3: "Đạt",
      ngayBdKhoiCong: "2026-04-10",
      luyKeGiaTriHdAB: 14.5,
      buTienDo: "Đang chạy",
      khQaQc: "Nghiệm thu cao độ nền đường lu lèn K95",
      kqQaQc: "Một số điểm chưa đạt độ chặt yêu cầu",
      dgQaQc: "Yêu cầu lu lèn bổ sung và thí nghiệm lại",
      khThiCong: "Rải cấp phối đá dăm loại II dày 15cm",
      kqThiCong: "Hoàn thành rải cấp phối đá dăm 500m dài đường trục chính",
      dgThiCong: "Nhà thầu huy động đủ thiết bị lu lèn và xe téc nước",
      t1Kh: "Đắp đất nền đường đạt cao độ thiết kế",
      t1Kq: "Đạt 100% khối lượng đắp đất",
      t1Dg: "Đạt",
      t2Kh: "Lu lèn nền đường đạt độ chặt K95",
      t2Kq: "Đã thí nghiệm đạt 8/10 vị trí, 2 vị trí lu lại",
      t2Dg: "Cần hỗ trợ",
      t3Kh: "Rải đá dăm cấp phối loại II đoạn km0-km1",
      t3Kq: "Đã rải đá dăm đạt chiều dài 500m",
      t3Dg: "Đạt",
      t4Kh: "Đổ bê tông vỉa hè và bó vỉa hè đoạn cảnh quan",
      t4Kq: "Hoàn thành đổ 300m bó vỉa",
      t4Dg: "Đạt"
    }
  ],
  so01: [
    {
      stt: 1,
      packageId: 1,
      loaiHoSo: "Lệnh khởi công",
      tenSpham: "Lệnh khởi công số 01/LK-VSV",
      linkLuuTru: "https://drive.google.com/file/d/1lk-vsv01/view",
      ngayHt: "2026-01-10",
      nguoiLap: "Nguyễn Văn A",
      nguoiDuyet: "Phó Giám đốc Ban",
      ttDuyet: "Đã duyệt"
    },
    {
      stt: 2,
      packageId: 1,
      loaiHoSo: "Biên bản bàn giao mặt bằng",
      tenSpham: "Biên bản bàn giao mặt bằng mốc định vị móng",
      linkLuuTru: "https://drive.google.com/file/d/1bbbg-vsv01/view",
      ngayHt: "2026-01-11",
      nguoiLap: "Nguyễn Văn A",
      nguoiDuyet: "Đại diện CĐT",
      ttDuyet: "Đã duyệt"
    },
    {
      stt: 3,
      packageId: 2,
      loaiHoSo: "Hồ sơ năng lực nhà thầu",
      tenSpham: "Hồ sơ năng lực Nhà thầu Cơ điện M&E Việt Nam",
      linkLuuTru: "https://drive.google.com/file/d/1hsnl-mevn/view",
      ngayHt: "2026-02-20",
      nguoiLap: "Trần Thị B",
      nguoiDuyet: "Trưởng phòng Kế hoạch",
      ttDuyet: "Đã duyệt"
    },
    {
      stt: 4,
      packageId: 5,
      loaiHoSo: "Bảo hiểm",
      tenSpham: "Đơn bảo hiểm công trình số BH-2026-CT05",
      linkLuuTru: "https://drive.google.com/file/d/1bh-ct05/view",
      ngayHt: "2026-04-05",
      nguoiLap: "Hoàng Văn E",
      nguoiDuyet: "Trưởng phòng Kế hoạch",
      ttDuyet: "Đã duyệt"
    },
    {
      stt: 5,
      packageId: 4,
      loaiHoSo: "Bảo lãnh",
      tenSpham: "Thư bảo lãnh thực hiện hợp đồng Ngân hàng BIDV",
      linkLuuTru: "https://drive.google.com/file/d/1bl-bidv-ct04/view",
      ngayHt: "2026-05-20",
      nguoiLap: "Phạm Văn D",
      nguoiDuyet: "Trưởng phòng Kế hoạch",
      ttDuyet: "Đăng trình duyệt"
    }
  ],
  so02: [
    {
      stt: 1,
      packageId: 1,
      thang: "Tháng 06/2026",
      loaiTaiLieu: "Kế hoạch tổng thể",
      noiDungChinh: "Kế hoạch tổng thể biện pháp thi công tường vây sâu 24m quanh hố đào",
      datYckt: "Đạt",
      linkTaiLieu: "https://drive.google.com/file/d/1khtongthe-ct01/view",
      ttLap: "Đã hoàn thành",
      ttDuyet: "Đã duyệt",
      nguoiLap: "Nguyễn Văn A",
      nguoiDuyet: "Giám đốc Dự án",
      ngayDuyet: "2026-05-25"
    },
    {
      stt: 2,
      packageId: 1,
      thang: "Tháng 06/2026",
      loaiTaiLieu: "Biện pháp thi công",
      noiDungChinh: "Biện pháp gia cố đất nền xung quanh hầm tự hoại",
      datYckt: "Đạt",
      linkTaiLieu: "https://drive.google.com/file/d/1bptc-giaco-ct01/view",
      ttLap: "Đã hoàn thành",
      ttDuyet: "Đã duyệt",
      nguoiLap: "Nguyễn Văn A",
      nguoiDuyet: "Tư vấn giám sát trưởng",
      ngayDuyet: "2026-05-28"
    },
    {
      stt: 3,
      packageId: 2,
      thang: "Tháng 06/2026",
      loaiTaiLieu: "Tiến độ chi tiết",
      noiDungChinh: "Tiến độ chi tiết chế tạo, thử nghiệm vỏ tủ trạm kiosk 1000kVA",
      datYckt: "Chưa đạt",
      linkTaiLieu: "https://drive.google.com/file/d/1tdct-trakiosk-ct02/view",
      ttLap: "Đang lập",
      ttDuyet: "Chờ duyệt",
      nguoiLap: "Trần Thị B",
      nguoiDuyet: "Kỹ sư Điện CĐT",
      ngayDuyet: ""
    },
    {
      stt: 4,
      packageId: 5,
      thang: "Tháng 06/2026",
      loaiTaiLieu: "Kế hoạch tổng thể",
      noiDungChinh: "Kế hoạch thảm bê tông nhựa mặt đường nội bộ chính phân khu sảnh",
      datYckt: "Đạt",
      linkTaiLieu: "https://drive.google.com/file/d/1kh-thamnhua-ct05/view",
      ttLap: "Đã hoàn thành",
      ttDuyet: "Đã duyệt",
      nguoiLap: "Hoàng Văn E",
      nguoiDuyet: "Giám đốc Dự án",
      ngayDuyet: "2026-05-30"
    }
  ],
  so03: [
    {
      maPs: "PS-001",
      packageId: 1,
      ngayPs: "2026-02-15",
      loai: "Thay đổi thiết kế",
      moTa: "Thay đổi chiều sâu ngàm tường vây từ 22m xuống 24m do gặp lớp cát chảy",
      nguyenNhan: "Hồ sơ khảo sát địa chất chưa chi tiết hết các lớp đất yếu cục bộ",
      deXuat: "Tăng chiều dài thép hình gia cường và bê tông đổ tường vây",
      giaTri: 1.5,
      anhHuongTd: 5,
      linkHoSo: "https://drive.google.com/file/d/1ps01-ct01/view",
      ttDuyet: "Đã duyệt",
      nguoiDuyet: "Nguyễn Tuấn Hải (Giám đốc Ban)",
      ngayDuyet: "2026-02-28",
      noiDungDieuChinh: "Đồng ý tăng 2m tường vây cho 5 phân đoạn có nguy cơ sạt lở. Chi phí tính bổ sung theo đơn giá hợp đồng."
    },
    {
      maPs: "PS-002",
      packageId: 1,
      ngayPs: "2026-05-10",
      loai: "Tăng khối lượng",
      moTa: "Bổ sung thép đai gia cường cọc khoan nhồi D1200",
      nguyenNhan: "Yêu cầu tăng khả năng chịu lực tối ưu khi có tải động lớn bên trên",
      deXuat: "Bổ sung đai xoắn D12 khoảng cách a100 thay vì a150",
      giaTri: 0.8,
      anhHuongTd: 2,
      linkHoSo: "https://drive.google.com/file/d/1ps02-ct01/view",
      ttDuyet: "Chờ duyệt",
      nguoiDuyet: "",
      ngayDuyet: "",
      noiDungDieuChinh: "Đang trình Tư vấn thiết kế tính toán lại khả năng chịu lực tối ưu."
    },
    {
      maPs: "PS-003",
      packageId: 2,
      ngayPs: "2026-06-12",
      loai: "Phát sinh ngoài hợp đồng",
      moTa: "Bổ sung hệ thống chống sét trực tiếp bằng kim thu lôi ESE bảo vệ Trạm biến áp ngoài trời",
      nguyenNhan: "Thiết kế gốc thiếu hạng mục chống sét cho thiết bị ngoài trời",
      deXuat: "Lắp đặt kim thu sét Stormaster 30 bán kính bảo vệ 65m và cáp đồng thoát sét thoát xuống đất",
      giaTri: 0.45,
      anhHuongTd: 3,
      linkHoSo: "https://drive.google.com/file/d/1ps01-ct02/view",
      ttDuyet: "Chờ duyệt",
      nguoiDuyet: "",
      ngayDuyet: "",
      noiDungDieuChinh: "Phòng kỹ thuật đang kiểm tra cao độ kim thu sét để không làm ảnh hưởng mỹ quan sảnh chính bên cạnh."
    }
  ],
  so04: [
    {
      maYc: "YC-001",
      packageId: 1,
      ngayYc: "2026-02-01",
      loaiYc: "Vật tư đặc thù",
      vatTu: "Bột sét siêu mịn Bentonite API của Ấn Độ",
      dacTa: "Dùng để tạo màng giữ vách hố khoan sâu trong lớp cát ngập nước, yêu cầu chứng chỉ CQ xuất xứ rõ ràng",
      kl: 120,
      dvt: "Tấn",
      giaTri: 0.72,
      trongNgoaiHd: "Trong hợp đồng",
      linkHoSo: "https://drive.google.com/file/d/1yc01-ct01/view",
      ttDuyet: "Đã duyệt",
      ngayCan: "2026-02-15",
      ttCungUng: "Đã bàn giao công trường"
    },
    {
      maYc: "YC-002",
      packageId: 2,
      ngayYc: "2026-06-05",
      loaiYc: "Thiết bị thuê ngoài",
      vatTu: "Xe cẩu siêu trường siêu trọng 250 Tấn",
      dacTa: "Cẩu hạ máy biến áp 4500kVA từ xe rơ-moóc vào bệ đặt trạm điện hầm B1",
      kl: 1,
      dvt: "Ca",
      giaTri: 0.18,
      trongNgoaiHd: "Ngoài hợp đồng",
      linkHoSo: "https://drive.google.com/file/d/1yc01-ct02/view",
      ttDuyet: "Chờ duyệt",
      ngayCan: "2026-07-05",
      ttCungUng: "Chưa mua"
    },
    {
      maYc: "YC-003",
      packageId: 4,
      ngayYc: "2026-06-20",
      loaiYc: "Biện pháp đặc biệt",
      vatTu: "Giàn treo cẩu lắp mặt dựng Chiller tầng mái",
      dacTa: "Lắp đặt hệ thống khung dầm thép đỡ xích kéo pa-lăng xích lắp ráp dàn ngưng tụ Chiller trên tầng mái kỹ thuật",
      kl: 1,
      dvt: "Hệ",
      giaTri: 0.35,
      trongNgoaiHd: "Ngoài hợp đồng",
      linkHoSo: "https://drive.google.com/file/d/1yc01-ct04/view",
      ttDuyet: "Chờ duyệt",
      ngayCan: "2026-07-15",
      ttCungUng: "Chưa mua"
    }
  ],
  so05: [
    {
      stt: 1,
      packageId: 2,
      ngayPhatHien: "2026-05-15",
      mucCham: 12,
      nguyenNhan: "Chậm tiến độ giao hàng tủ điện hạ thế tổng do tắc biên đường bộ nhập khẩu linh kiện",
      giaiPhapBu: "Tăng ca lắp đặt, chuyển phát hàng bằng đường hàng không",
      chiTietGiaiPhap: "Nhà thầu tự chịu chi phí bù chênh lệch vận chuyển hàng không cho cụm linh kiện tủ ACB để lắp ráp vỏ tủ tại Việt Nam.",
      mocCamKet: "2026-07-10",
      linkPhuongAn: "https://drive.google.com/file/d/1pa-budt-ct02/view",
      ttDuyet: "Đã phê duyệt phương án",
      kqThucHienBu: "Đã vận chuyển lô linh kiện ACB về đến xưởng lắp ráp quận 9. Tiến độ vỏ tủ đang được đẩy nhanh.",
      ttThucHien: "Đang triển khai bù"
    },
    {
      stt: 2,
      packageId: 5,
      ngayPhatHien: "2026-05-02",
      mucCham: 8,
      nguyenNhan: "Vướng mặt bằng đổ thải đá dăm làm chậm khâu san lấp mặt bằng",
      giaiPhapBu: "Điều động thêm 3 xe lu cỡ lớn và 5 xe ben vận chuyển đêm",
      chiTietGiaiPhap: "Ban điều hành hỗ trợ xin giấy phép vận tải đêm của Sở GTVT để nhà thầu dọn bãi đất thải nhanh gấp đôi tiến độ cam kết.",
      mocCamKet: "2026-06-15",
      linkPhuongAn: "https://drive.google.com/file/d/1pa-budt-ct05/view",
      ttDuyet: "Đã phê duyệt phương án",
      kqThucHienBu: "Đã dọn dẹp sạch bãi thải vào ngày 12/06. Toàn bộ nền đường đã được lu lèn K95 đạt chất lượng.",
      ttThucHien: "Đã bắt kịp tiến độ"
    }
  ]
};
